### ISSUE TITLE
Missing nanoflan_two.hpp file

### ISSUE THREAD

**Issue by curtismuntz** [peteflorence/NanoMap#1]
I'm attempting to build this project and I noticed that you may be missing a file.

Inside of kd_tree_two.h, there is a ` #include "nanoflann_two.hpp"` which does not seem to be part of this repository.

I cannot find any other references to this file using a github search that are outside this repo. Perhaps this a missing file? or does another library provide this file?

Thanks!

**Comment by peteflorence** [comment]
Hi Curtis, thanks for your interest.  I just pushed a repo that builds in ROS with a `CMakeLists.txt`, shows examples of how to use the NanoMap interface, and is code that was flight tested in the weeks leading up to our Darpa FLA challenge and used there for the whole week's worth of competition flights.  This use of NanoMap is not as clean as I'd like, but it works and has been tested pretty heavily.  That repo is [here](https://github.com/peteflorence/quadrotor-nanomap).

I'll be working on some code clean up and documentation in the next couple weeks, but not next few days.  Until then, I hope that repo helps.

Let me know if you have any more questions.

**Comment by peteflorence** [comment]
Curtis, to give a little more guidance in that repo -- ctrl+f for `nanomap` in `motion_selector_node.cpp` and in `depth_image_collision_evaluator.cpp`.  The node (`motion_selector_node.cpp`) handles pub/sub and inputs data into nanomap and calls its visualizer.  The `depth_image_collision_evaluator.cpp` is where the query into nanomap happens, which is used by `motion_selector.cpp` to evaluate collision probability of a motion primitive library (`motion_library.cpp`).

**Comment by curtismuntz** [comment]
Thanks Pete. Looks like the nanoflann_two.hpp file is in that repo. I'll take a look at that repo for more guidance. In general, do you expect that repo's version of Nanomap to be kept more up to date than this one? I'll star both repos to keep up to date. I have use for nanomap in some projects and would be willing to contribute some PRs if you are interested.

**Comment by peteflorence** [comment]
Curtis, awesome, PRs would be much encouraged!

This repo (not the other) will be getting some commits (unit tests, benchmarking, and code clean up) over the next 1.5 months.  But yes the other one is fully functional for now.  PRs encouraged for either (but this one if it's related to the core Nanomap code).  Thanks!

**Comment by peteflorence** [comment]
hi @curtismuntz -- please see this new repo:  https://github.com/peteflorence/nanomap_ros

In README is linked explanation video.

**Comment by curtismuntz** [comment]
Awesome Pete! Thanks for the update.
